### ISSUE TITLE
Running MaxQuant in RHEL 7 with Sciex WIFF files

### ISSUE THREAD

**Issue by indianAppl** [LabKey/MaxQuant#52]
Hello Team, 

I am trying run MaxQuant 2.0.3.1 in our Linux server which hosts a RHEL 7. The files I am trying to run are acquired on Sciex TripleTOF 6600 and are DDA run. The error I am facing is as following:
```
Unhandled exception. System.Exception: Exception during execution of external process: 44310 Unhandled exception. System.Runtime.InteropServices.MarshalDirectiveException: Cannot marshal 'parameter #8': Invalid managed/unmanaged type combination (Marshaling to and from COM interface pointers isn't supported).
   at Clearcore2.StructuredStorage.COM.StgFunctions.StgOpenStorageEx(String pwcsName, UInt32 grfMode, UInt32 stgfmt, UInt32 grfAttrs, IntPtr pStgOptions, IntPtr reserved2, Guid& riid, Object& ppObjectOpen)
   at Clearcore2.StructuredStorage.COM.StgFunctions.OpenStorage(String filePath, StgMode mode)
   at Clearcore2.StructuredStorage.StgStorageCOM.OpenFileCOM(String filePath, StgMode mode, Object cacheKey)
   at Clearcore2.StructuredStorage.StgStorage.OpenFile(String filePath, StgMode mode, Object cacheObject)
   at Clearcore2.Data.WiffReader.WiffStorageProviderDefaultImplementation.OpenFile()
   at Clearcore2.Data.WiffReader.WiffStorage..ctor(IWiffStorageProvider storage)
   at Clearcore2.Data.WiffReader.WiffStorageOwner.GetWiffStorage()
   at Clearcore2.Data.WiffReader.WiffStorageOwner.get_WiffStorage()
   at Clearcore2.Data.WiffReader.WiffStorageOwner.GetWiffStorage()
   at Clearcore2.Data.WiffReader.WiffStorageOwner.get_WiffStorage()
   at Clearcore2.Data.WiffReader.WiffSampleSubTree.get_SampleCount()
   at Clearcore2.Data.WiffReader.WiffFile.get_SampleCount()
   at Clearcore2.Data.AnalystDataProvider.AnalystWiffDataProvider.GetBasicSampleInfos(String pathToSourceFile)
   at Clearcore2.Data.AnalystDataProvider.BatchImp.GetSampleNames()
   at PluginRawSciexCore.SciexWiff..ctor(String filename)
   at PluginRawSciexCore.SciexWiffRawFile.PreInit()
   at BaseLibS.Ms.RawFile.InitFromRawFile()
   at BaseLibS.Ms.RawFile.Init(String path1)
   at MsLib.Raw.RawFileUtil.CreateRawFile(String path)
   at MaxQuantLibS.Domains.Peptides.Data.GenericRun.<>c__DisplayClass10_0.<.ctor>b__0()
   at MaxQuantLibS.Domains.Peptides.Data.GenericRun.get_RawFile()
   at MaxQuantLibS.Domains.Peptides.Data.GenericRunLayer.get_RawFileLayer()
   at MaxQuantLibS.Domains.Peptides.Features.FeatureDetectionUtil.AssembleRunInfo(String mqparFile, Int32 fileIndex)
   at MaxQuantLibS.Domains.Peptides.Work.AssembleRunInfo.Calculation(String[] args, Responder responder)
   at MaxQuantLibS.Domains.Peptides.Work.MaxQuantWorkDispatcherUtil.PerformTask(Int32 taskType, String[] args, Responder responder)
   at MaxQuantLibS.Base.MaxQuantUtils.Run(Int32 softwareId, Int32 taskType, String[] args, Responder responder)
   at MaxQuantTaskCore.Program.Function(String[] args, Responder responder)
   at Utils.Util.ExternalProcess.Run(String[] args, Boolean debug)
   at MaxQuantTaskCore.Program.Main(String[] args)

   at QueueingSystem.WorkDispatcher.ProcessSingleRunExternalProcess(Int32 taskIndex, Int32 threadIndex)
   at QueueingSystem.WorkDispatcher.DoWork(Int32 taskIndex, Int32 threadIndex)
   at QueueingSystem.WorkDispatcher.Work(Object threadIndex)
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
Aborted (core dumped)
```
**Now the problem is I can't understand if the problem is :**
1. Running WIFF files in linux ?
2. Running out of resource ?
3. Any mistake in the MQ parameter file ?

Regards
Sangramjit

**Comment by labkey-jeckels** [comment]
Hi Sangramjit. This isn't the GitHub repo for MaxQuant itself. It's a LabKey Server module that imports MaxQuant data. Unfortunately, we're not experts in MaxQuant itself.
